"""Add clarification fields

Revision ID: 03afade9baee
Revises: 91164751d7b8
Create Date: 2025-05-14 19:41:06.705259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03afade9baee'
down_revision: Union[str, None] = '91164751d7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('queries', sa.Column('clarification_requested', sa.Boolean(), nullable=True))
    op.add_column('queries', sa.Column('clarification_type', sa.String(length=50), nullable=True))
    op.add_column('queries', sa.Column('processed_text', sa.Text(), nullable=True))
    op.add_column('queries', sa.Column('enhanced_text', sa.Text(), nullable=True))
    op.add_column('queries', sa.Column('engine_type', sa.String(length=20), nullable=True))
    op.add_column('queries', sa.Column('parent_query_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('queries', 'parent_query_id')
    op.drop_column('queries', 'engine_type')
    op.drop_column('queries', 'enhanced_text')
    op.drop_column('queries', 'processed_text')
    op.drop_column('queries', 'clarification_type')
    op.drop_column('queries', 'clarification_requested')
    # ### end Alembic commands ###
